### ISSUE TITLE
Exception thrown when using Selenoid Attribute

### ISSUE THREAD

**Issue by Armz10** [AutomateThePlanet/BELLATRIX#17]
When executing the sample test from class `SelenoidTests.cs` the following exceptions are thrown. I have installed Docker and using [Selenoid](https://github.com/aerokube/selenoid)

[`BrowserAttribute.cs`](https://github.com/AutomateThePlanet/BELLATRIX/blob/f2cb1a2422d3bca0ed28917bc73e74e40f5b4072/src/Bellatrix.Web/plugins/execution/Attributes/BrowserAttribute.cs#L122)
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Bellatrix.Web
  StackTrace:
   at Bellatrix.Web.BrowserAttribute.GetTestFullName(MemberInfo memberInfo, Type testClassType) in C:\Users\admin\Desktop\BELLATRIX-master\src\Bellatrix.Web\plugins\execution\Attributes\BrowserAttribute.cs:line 122
```
[
`NUnitBaseTest.cs`](https://github.com/AutomateThePlanet/BELLATRIX/blob/4c3cf2ec63ddd95584f2f9118eeb9bbc222f88a4/src/Bellatrix.Core/infrastructure/NUnitBaseTest.cs#L86)
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Bellatrix.Web
  StackTrace:
   at Bellatrix.Web.BrowserAttribute.GetTestFullName(MemberInfo memberInfo, Type testClassType) in C:\Users\admin\Desktop\BELLATRIX-master\src\Bellatrix.Web\plugins\execution\Attributes\BrowserAttribute.cs:line 122
   at Bellatrix.Web.SelenoidAttribute.CreateOptions(MemberInfo memberInfo, Type testClassType) in C:\Users\admin\Desktop\BELLATRIX-master\src\Bellatrix.Web\plugins\execution\Attributes\SelenoidAttribute.cs:line 153
   at Bellatrix.Web.Plugins.Browser.BrowserLifecyclePlugin.GetCurrentBrowserConfiguration(PluginEventArgs e) in C:\Users\admin\Desktop\BELLATRIX-master\src\Bellatrix.Web\plugins\execution\BrowserLifecyclePlugin.cs:line 192
   at Bellatrix.Web.Plugins.Browser.BrowserLifecyclePlugin.PreTestsArrange(Object sender, PluginEventArgs e) in C:\Users\admin\Desktop\BELLATRIX-master\src\Bellatrix.Web\plugins\execution\BrowserLifecyclePlugin.cs:line 46
   at Bellatrix.Plugins.PluginProvider.RaiseClassTestEvent(EventHandler`1 eventHandler, TestOutcome testOutcome, Type testClassType, List`1 arguments) in C:\Users\admin\Desktop\BELLATRIX-master\src\Bellatrix.Core\plugins\PluginProvider.cs:line 120
   at Bellatrix.Plugins.PluginProvider.PreTestsArrange(Type testClassType, List`1 arguments) in C:\Users\admin\Desktop\BELLATRIX-master\src\Bellatrix.Core\plugins\PluginProvider.cs:line 52
   at Bellatrix.NUnitBaseTest.OneTimeArrangeAct() in C:\Users\admin\Desktop\BELLATRIX-master\src\Bellatrix.Core\infrastructure\NUnitBaseTest.cs:line 79

  This exception was originally thrown at this call stack:
    Bellatrix.Web.BrowserAttribute.GetTestFullName(System.Reflection.MemberInfo, System.Type) in BrowserAttribute.cs
    Bellatrix.Web.SelenoidAttribute.CreateOptions(System.Reflection.MemberInfo, System.Type) in SelenoidAttribute.cs
    Bellatrix.Web.Plugins.Browser.BrowserLifecyclePlugin.GetCurrentBrowserConfiguration(Bellatrix.Plugins.PluginEventArgs) in BrowserLifecyclePlugin.cs
    Bellatrix.Web.Plugins.Browser.BrowserLifecyclePlugin.PreTestsArrange(object, Bellatrix.Plugins.PluginEventArgs) in BrowserLifecyclePlugin.cs
    Bellatrix.Plugins.PluginProvider.RaiseClassTestEvent(System.EventHandler<Bellatrix.Plugins.PluginEventArgs>, Bellatrix.Plugins.TestOutcome, System.Type, System.Collections.Generic.List<object>) in PluginProvider.cs
    Bellatrix.Plugins.PluginProvider.PreTestsArrange(System.Type, System.Collections.Generic.List<object>) in PluginProvider.cs
    Bellatrix.NUnitBaseTest.OneTimeArrangeAct() in NUnitBaseTest.cs
```

[`SelenoidTests.cs`](https://github.com/AutomateThePlanet/BELLATRIX/blob/21ccebb5697091b275d6844b7dda9291c6e289e2/templates/Bellatrix.Web.GettingStarted/21.%20Grid%20and%20Cloud%20Integrations/21.5.%20Execute%20in%20Selenoid/SelenoidTests.cs#L16)
```
[TestFixture]
[Selenoid(BrowserType.Chrome, "99", Lifecycle.RestartEveryTime)]
public class SelenoidTests : NUnit.WebTest
{
        [Test]
        [Selenoid(BrowserType.Chrome, "99", Lifecycle.RestartEveryTime)]
        public void PromotionsPageOpened_When_PromotionsButtonClicked()
        {
            App.Navigation.Navigate("http://demos.bellatrix.solutions/");

            var promotionsLink = App.Components.CreateByLinkText<Anchor>("Promotions");

            promotionsLink.Click();
        }
```
`testFrameworkSettings.Debug.json`
```
    "executionSettings": {
      "executionType": "regular",
      "defaultBrowser": "chrome",
      "defaultLifeCycle": "restart every time",
      "resolution": "1920x1080",
      "browserVersion": "99",
      "isCloudRun": "false",
      "url": "http://localhost:4444/wd/hub",
      "arguments": [
        {
          "acceptInsecureCerts": "true",
          "name": "{runName}",
          "videoName": "{runName}.{timestamp}.mp4",
          "logName": "{runName}.{timestamp}.log",
          "enableVNC": "true",
          "enableVideo": "true",
          "enableLog": "true",
          "screenResolution": "1920x1080x24"
        }
      ]
```

`Browsers.json` file located at `C:\Users\admin\.aerokube\selenoid`
```
{
    "chrome": {
        "default": "100.0",
        "versions": {
            "100.0": {
                "image": "selenoid/chrome:100.0",
                "port": "4444",
                "path": "/"
            },
            "99.0": {
                "image": "selenoid/chrome:99.0",
                "port": "4444",
                "path": "/"
            }
        }
    },
    "firefox": {
        "default": "98.0",
        "versions": {
            "97.0": {
                "image": "selenoid/firefox:97.0",
                "port": "4444",
                "path": "/wd/hub"
            },
            "98.0": {
                "image": "selenoid/firefox:98.0",
                "port": "4444",
                "path": "/wd/hub"
            }
        }
    },
    "opera": {
        "default": "85.0",
        "versions": {
            "84.0": {
                "image": "selenoid/opera:84.0",
                "port": "4444",
                "path": "/"
            },
            "85.0": {
                "image": "selenoid/opera:85.0",
                "port": "4444",
                "path": "/"
            }
        }
    }
}

```

**Comment by angelovstanton** [comment]
Two points here. First, if you intend to use Selenoid for the whole run on the same browser + version then you can use the default configuration. Second, maybe you should investigate how to use the native Selenium Docker Grid since Selenoid lacks of maintenance recently and doesn't support Selenium 4.0 and we already experience problems with it after the upgrade. Probably the exception you got is because of it. They don't support the new protocol.
